= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS / VMC
--
AWS は、次の構成でNetAppストレージをサポートしています。

* ゲスト接続ストレージとしての FSx ONTAP
* ゲスト接続ストレージとしてのCloud Volumes ONTAP (CVO)
* 補助的なNFSデータストアとしてのFSx ONTAP


詳細を表示link:../vmware/vmw-aws-vmc-guest-storage.html["VMCのゲスト接続ストレージオプション"]。詳細を表示link:../vmware/vmw-aws-vmc-nfs-ds-config.html["VMC の補足 NFS データストア オプション"]。

詳細を表示link:../vmware/vmw-aws-vmc-guest-storage.html["VMCのゲスト接続ストレージオプション"]。詳細を表示link:../vmware/vmw-aws-vmc-nfs-ds-config.html["VMC の補足 NFS データストア オプション"]。

--
.Azure / AVS
--
Azure は、次の構成のNetAppストレージをサポートしています。

* ゲスト接続ストレージとしてのAzure NetApp Files (ANF)
* ゲスト接続ストレージとしてのCloud Volumes ONTAP (CVO)
* 補助的な NFS データストアとしてのAzure NetApp Files (ANF)


詳細を表示link:../vmware/vmw-azure-avs-guest-storage.html["AVS のゲスト接続ストレージ オプション"]。詳細を表示link:../vmware/vmw-azure-avs-nfs-ds-config.html["AVS の補足 NFS データストア オプション"]。

詳細を表示link:../vmware/vmw-azure-avs-guest-storage.html["AVS のゲスト接続ストレージ オプション"]。詳細を表示link:../vmware/vmw-azure-avs-nfs-ds-config.html["AVS の補足 NFS データストア オプション"]。

--
.GCP / GCVE
--
Google Cloud は、次の構成のNetAppストレージをサポートしています。

* ゲスト接続ストレージとしてのCloud Volumes ONTAP (CVO)
* ゲスト接続ストレージとしてのGoogle Cloud NetApp Volumes (NetApp Volumes)
* 補助的な NFS データストアとしてのGoogle Cloud NetApp Volumes (NetApp Volumes)


詳細を表示link:../vmware/vmw-gcp-gcve-guest-storage.html["GCVE のゲスト接続ストレージ オプション"]。詳細を表示link:../vmware/vmw-gcp-gcve-nfs-ds-overview.html["GCVE の補足 NFS データストア オプション"]。

詳細を表示link:../vmware/vmw-gcp-gcve-guest-storage.html["GCVE のゲスト接続ストレージ オプション"]。詳細を表示link:../vmware/vmw-gcp-gcve-nfs-ds-overview.html["GCVE の補足 NFS データストア オプション"]。

詳細はこちらlink:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Google Cloud NetApp Volumesデータストアのサポート (NetAppブログ)"^]またはlink:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["Google Cloud NetApp Volumes をGoogle Cloud VMware Engine のデータストアとして使用する方法 (Google ブログ)"^]

--
====