---
sidebar: sidebar 
permalink: vmware/vmw-azure-avs-nfs-ds-overview.html 
keywords:  
summary:  
---
= ANFデータストアソリューションの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
成功している組織はすべて、変革と近代化の道を歩んでいます。このプロセスの一環として、企業は通常、既存の VMware 投資を活用しながらクラウドのメリットを活用し、移行、バースト、拡張、および災害復旧のプロセスを可能な限りシームレスにする方法を検討します。クラウドに移行する顧客は、弾力性とバースト、データセンターの撤退、データセンターの統合、サポート終了のシナリオ、合併、買収などの問題を評価する必要があります。各組織が採用するアプローチは、それぞれのビジネス上の優先順位に応じて異なります。クラウドベースの運用を選択する場合、適切なパフォーマンスと最小限の障害を備えた低コストのモデルを選択することが重要な目標です。適切なプラットフォームを選択することに加え、クラウドの展開と弾力性の力を最大限に引き出すには、ストレージとワークフローのオーケストレーションが特に重要です。



== ユースケース

Azure VMware ソリューションは顧客に独自のハイブリッド機能を提供しますが、ネイティブ ストレージ オプションが限られているため、ストレージ負荷の高いワークロードを持つ組織にとってその有用性が制限されています。ストレージはホストに直接結び付けられているため、ストレージを拡張する唯一の方法はホストを追加することであり、これによりストレージを集中的に使用するワークロードのコストが 35 ～ 40% 以上増加する可能性があります。これらのワークロードには追加の処理能力ではなく追加のストレージが必要ですが、追加のホストに対して料金を支払う必要があります。

次のシナリオを考えてみましょう。顧客は処理能力 (vCPU/vMem) のために 6 台のホストを必要としていますが、ストレージについてもかなりの要件があります。評価によると、ストレージ要件を満たすには 12 台のホストが必要です。これにより、実際に必要なのはストレージの増設だけなのに、追加の処理能力をすべて購入する必要があるため、全体的な TCO が増加します。これは、移行、災害復旧、バースト、開発/テストなど、あらゆるユースケースに適用できます。

Azure VMware Solution のもう 1 つの一般的な使用例は、災害復旧 (DR) です。ほとんどの組織は、確実な DR 戦略を持っていません。あるいは、DR のためだけにゴースト データセンターを運用することを正当化するのに苦労するかもしれません。管理者は、パイロットライト クラスターまたはオンデマンド クラスターを使用して、ゼロ フットプリントの DR オプションを検討できます。そうすれば、ホストを追加せずにストレージを拡張することができ、魅力的な選択肢になる可能性があります。

まとめると、ユースケースは次の 2 つの方法で分類できます。

* ANF データストアを使用したストレージ容量の拡張
* ANF データストアを、オンプレミスまたはソフトウェア定義データセンター (SDDC) 間の Azure リージョン内からのコスト最適化された復旧ワークフローのディザスター リカバリー ターゲットとして使用します。このガイドでは、 Azure NetApp Files を使用してデータストアに最適化されたストレージ (現在パブリック プレビュー) を提供するとともに、Azure VMware ソリューションのクラス最高のデータ保護と DR 機能について説明し、vSAN ストレージからストレージ容量をオフロードできるようにします。



NOTE: ANF データストアの使用に関する追加情報については、お住まいの地域のNetAppまたは Microsoft ソリューション アーキテクトにお問い合わせください。



== Azure の VMware Cloud オプション



=== Azure VMware ソリューション

Azure VMware Solution (AVS) は、Microsoft Azure パブリック クラウド内で完全に機能する VMware SDDC を提供するハイブリッド クラウド サービスです。 AVS は、Microsoft によって完全に管理およびサポートされ、Azure インフラストラクチャを使用する VMware によって検証されたファーストパーティ ソリューションです。そのため、お客様は、コンピューティング仮想化用の VMware ESXi、ハイパーコンバージド ストレージ用の vSAN、ネットワークとセキュリティ用の NSX を利用できると同時に、Microsoft Azure のグローバルな展開、クラス最高のデータ センター設備、ネイティブ Azure サービスとソリューションの豊富なエコシステムへの近接性を活用できます。  Azure VMware Solution SDDC とAzure NetApp Files を組み合わせることで、最小限のネットワーク待機時間で最高のパフォーマンスが得られます。

使用するクラウドに関係なく、VMware SDDC が展開されると、初期クラスタには次のコンポーネントが含まれます。

* コンピューティング仮想化用の VMware ESXi ホストと管理用の vCenter サーバー アプライアンス。
* 各 ESXi ホストの物理ストレージ資産を組み込んだ VMware vSAN ハイパーコンバージド ストレージ。
* 仮想ネットワークとセキュリティのための VMware NSX と、管理用の NSX Manager クラスタ。




== まとめ

オールクラウドまたはハイブリッド クラウドのどちらをターゲットにしているかに関係なく、Azure NetAppファイルは、データ要件をアプリケーション レイヤーにシームレスにすることで TCO を削減しながら、ファイル サービスとともにアプリケーション ワークロードを展開および管理するための優れたオプションを提供します。ユース ケースがどのようなものであっても、Azure VMware Solution とAzure NetApp Filesを併せて選択すると、クラウドのメリットの迅速な実現、オンプレミスと複数のクラウドにわたる一貫性のあるインフラストラクチャと運用、ワークロードの双方向の移植性、エンタープライズ レベルの容量とパフォーマンスが実現します。これは、ストレージを接続するために使用される、使い慣れたプロセスと手順と同じです。覚えておいてください。変更されたのはデータの位置と新しい名前だけです。ツールとプロセスはすべて同じままで、 Azure NetApp Files は全体的な展開の最適化に役立ちます。



== まとめ

このドキュメントの主なポイントは次のとおりです。

* Azure NetApp Files をAVS SDDC 上のデータストアとして使用できるようになりました。
* アプリケーションの応答時間を向上させ、より高い可用性を実現し、必要なときに必要な場所でワークロード データにアクセスできるようにします。
* シンプルで即時のサイズ変更機能により、vSAN ストレージの全体的な複雑さを簡素化します。
* 動的な再形成機能を使用して、ミッションクリティカルなワークロードのパフォーマンスを保証します。
* Azure VMware Solution Cloud が宛先である場合、 Azure NetApp Files は最適化された展開に適したストレージ ソリューションです。




== 詳細情報の入手方法

このドキュメントに記載されている情報の詳細については、次の Web サイト リンクを参照してください。

* Azure VMware ソリューションのドキュメント
+
https://docs.microsoft.com/en-us/azure/azure-vmware/["https://docs.microsoft.com/en-us/azure/azure-vmware/"^]

* Azure NetApp Files のドキュメント
+
https://docs.microsoft.com/en-us/azure/azure-netapp-files/["https://docs.microsoft.com/en-us/azure/azure-netapp-files/"^]

* Azure NetApp Filesデータストアを Azure VMware Solution ホストに接続する (プレビュー)
+
https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?tabs=azure-portal/["https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?tabs=azure-portal/"^]


