---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-storage.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, cloud volumes ontap, cvo, datastore, fsx, fsx ontap 
summary:  
---
= パブリッククラウドプロバイダー向けのNetAppストレージオプション
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
3 大ハイパースケーラーにおけるストレージとしてのNetAppのオプションを検討します。

[role="tabbed-block"]
====
.AWS / VMC
--
AWS は、次の構成でNetAppストレージをサポートしています。

* ゲスト接続ストレージとしての FSx ONTAP
* ゲスト接続ストレージとしてのCloud Volumes ONTAP (CVO)
* 補助的なNFSデータストアとしてのFSx ONTAP


詳細を表示link:aws-guest.html["VMCのゲスト接続ストレージオプション"]。詳細を表示link:aws-native-nfs-datastore-option.html["VMC の補足 NFS データストア オプション"]。

--
.Azure / AVS
--
Azure は、次の構成のNetAppストレージをサポートしています。

* ゲスト接続ストレージとしてのAzure NetApp Files (ANF)
* ゲスト接続ストレージとしてのCloud Volumes ONTAP (CVO)
* 補助的な NFS データストアとしてのAzure NetApp Files (ANF)


詳細を表示link:azure-guest.html["AVS のゲスト接続ストレージ オプション"]。詳細を表示link:azure-native-nfs-datastore-option.html["AVS の補足 NFS データストア オプション"]。

--
.GCP / GCVE
--
Google Cloud は、次の構成のNetAppストレージをサポートしています。

* ゲスト接続ストレージとしてのCloud Volumes ONTAP (CVO)
* ゲスト接続ストレージとしてのGoogle Cloud NetApp Volumes (NetApp Volumes)
* 補助的な NFS データストアとしてのGoogle Cloud NetApp Volumes (NetApp Volumes)


詳細を表示link:gcp-guest.html["GCVE のゲスト接続ストレージ オプション"]。詳細を表示link:gcp-ncvs-datastore.html["GCVE の補足 NFS データストア オプション"]。

詳細はこちらlink:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Google Cloud NetApp Volumesデータストアのサポート (NetAppブログ)"^]またはlink:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["Google Cloud NetApp Volumes をGoogle Cloud VMware Engine のデータストアとして使用する方法 (Google ブログ)"^]

--
====