---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-summary.html 
keywords: NetApp Solutions, hybrid, Multicloud, enterprise hybrid cloud, hyperscalers, vmware 
summary:  
---
= 要約と結論: VMware とNetApp のハイブリッド マルチクラウドを組み合わせる理由
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Cloud Volumes と大手ハイパースケーラー向けの VMware ソリューションを組み合わせることで、ハイブリッド クラウドを活用したい組織に大きな可能性がもたらされます。このセクションの残りの部分では、 NetApp Cloud Volumes を統合することで真のハイブリッド マルチクラウド機能を実現できることを示すユースケースを紹介します。



== ユースケース1: ストレージの最適化

RVtools 出力を使用してサイズ設定を実行する場合、処理能力 (vCPU/vMem) のスケールがストレージと並行していることが常に明らかになります。多くの場合、組織は、ストレージ スペースが、処理能力に必要な量をはるかに超えるクラスターのサイズを要求する状況に陥ります。

NetApp Cloud Volumes を統合することで、組織はプラットフォームの再設定、IP の変更、アーキテクチャの変更を必要とせず、シンプルな移行アプローチで vSphere ベースのクラウド ソリューションを実現できます。さらに、この最適化により、vSphere で必要なホスト数を最小限に抑えながら、ストレージ フットプリントを拡張できますが、ストレージ階層、セキュリティ、または使用可能なファイルには変更が加えられません。これにより、導入を最適化し、全体的な TCO を 35～45% 削減できます。この統合により、ウォーム ストレージから実稼働レベルのパフォーマンスまで、ストレージを数秒で拡張することもできます。



== ユースケース2: クラウド移行

組織は、近づいているリースの期限、資本支出 (capex) から運用支出 (opex) に移行するという財務上の指示、すべてをクラウドに移行するというトップダウンの指示など、さまざまな理由から、オンプレミスのデータ センターからパブリック クラウドにアプリケーションを移行するようプレッシャーを受けています。

スピードが重要な場合、クラウドの特定の IaaS プラットフォームに適応するためにアプリケーションを再プラットフォーム化およびリファクタリングするのは時間がかかり、コストも高く、数か月かかることもよくあるため、合理化された移行アプローチのみが実現可能です。  NetApp Cloud Volumes と、ゲスト接続ストレージ用の帯域幅効率の高いSnapMirrorレプリケーション (アプリケーション整合性のあるスナップショット コピーと HCX を組み合わせた RDM、クラウド固有の移行 (Azure Migrate など)、または VM をレプリケートするためのサードパーティ製品を含む) を組み合わせることで、この移行は、時間のかかる I/O フィルター メカニズムに依存するよりもさらに簡単になります。



== ユースケース3: データセンターの拡張

季節的な需要の急増や、単に安定した有機的成長によりデータセンターの容量が限界に達した場合、クラウドでホストされる VMware とNetApp Cloud Volumes に移行するのが簡単な解決策です。  NetApp Cloud Volumes を活用すると、可用性ゾーン全体にわたる高可用性と動的なスケーリング機能が提供され、ストレージの作成、レプリケーション、拡張が非常に簡単になります。  NetApp Cloud Volumes を活用すると、ストレッチ クラスタの必要性を克服し、ホスト クラスタの容量を最小限に抑えることができます。



== ユースケース #4: クラウドへの災害復旧

従来のアプローチでは、災害が発生した場合、クラウドに複製された VM を復元するには、クラウド独自のハイパーバイザー プラットフォームに変換する必要があり、これは危機時に処理すべきタスクではありません。

オンプレミスからのSnapCenterおよびSnapMirrorレプリケーションとパブリック クラウド仮想化ソリューションを使用してゲスト接続ストレージにNetApp Cloud Volumes を使用することで、クラウド固有のリカバリ ツール (Azure Site Recovery など) または Veeam などの同等のサードパーティ ツールとともに、完全に一貫性のある VMware SDDC インフラストラクチャ上で VM レプリカをリカバリできる、より優れた災害復旧アプローチを考案できます。このアプローチにより、災害復旧訓練やランサムウェアからの復旧を迅速に実行することもできます。これにより、オンデマンドでホストを追加することで、テスト時や災害発生時に完全な本番環境に拡張することもできます。



== ユースケース #5: アプリケーションのモダナイゼーション

アプリケーションがパブリック クラウドに移行した後、組織は数百もの強力なクラウド サービスを活用して、アプリケーションを最新化し、拡張したいと考えるようになります。  NetApp Cloud Volumes を使用すると、アプリケーション データが vSAN にロックされず、Kubernetes を含む幅広いユース ケースでのデータ モビリティが可能になるため、モダナイゼーションのプロセスが簡単になります。



== まとめ

オールクラウドまたはハイブリッド クラウドのどちらをターゲットにしているかに関係なく、 NetApp Cloud Volumes は、データ要件をアプリケーション層にシームレスにすることで TCO を削減しながら、ファイル サービスとブロック プロトコルとともにアプリケーション ワークロードを導入および管理するための優れたオプションを提供します。

ユースケースに関係なく、お気に入りのクラウド/ハイパースケーラーをNetApp Cloud Volumes と組み合わせて選択することで、クラウドのメリット、オンプレミスと複数のクラウドにわたる一貫したインフラストラクチャと運用、ワークロードの双方向の移植性、エンタープライズ グレードの容量とパフォーマンスを迅速に実現できます。

これは、ストレージを接続するために使用される、使い慣れたプロセスと手順と同じです。覚えておいてください。新しい名前で変更されたのはデータの位置だけです。ツールとプロセスはすべて同じままで、 NetApp Cloud Volumes は全体的な導入の最適化に役立ちます。
