---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-dr-overview.html 
keywords: dr, draas, bluexp, disaster recovery, vmfs datastore, nfs datastore, overview 
summary: このドキュメントのセクションでは、オンプレミスの VMware VM の災害復旧を別の指定サイトに設定するためのBlueXP DRaaS の構成について説明します。 
---
= 概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
災害復旧は、すべての VMware 管理者にとって最も重要な事項です。  VMware は、サーバー全体を仮想マシンを構成する一連のファイルにカプセル化するため、管理者はクローン、スナップショット、レプリカなどのブロック ストレージ ベースの技術を利用してこれらの VM を保護します。  ONTAPアレイには、ボリューム データ、および指定されたデータストア LUN 上に存在する仮想マシンをあるサイトから別のサイトに転送するための組み込みレプリケーション機能が備わっています。 BlueXP DRaaS は vSphere と統合し、災害発生時にシームレスなフェイルオーバーとフェイルバックを実現するためにワークフロー全体を自動化します。ストレージ レプリケーションとインテリジェントな自動化を組み合わせることで、管理者は災害復旧計画を構成、自動化、テストできるだけでなく、災害発生時にそれらを簡単に実行できる手段も管理できるようになります。

VMware vSphere 環境での DR フェイルオーバーで最も時間のかかる部分は、DR サイトでの VM のインベントリ、登録、再構成、および電源投入に必要な手順の実行です。理想的なソリューションは、RPO (分単位で測定) と RTO (分から時間単位で測定) の両方が低いものです。  DR ソリューションで見落とされがちな要素の 1 つは、DR ソリューションを定期的に効率的にテストする機能です。

DR ソリューションを設計するには、次の要素を考慮してください。

* 目標復旧時間 (RTO)。  RTO とは、企業が災害からどれだけ早く回復できるか、より具体的には、ビジネス サービスを再び利用できるようにするために回復プロセスを実行するのにどれだけの時間がかかるかということです。
* 回復ポイント目標 (RPO)。  RPO は、災害が発生した時間に対して、回復されたデータが利用可能になってからどのくらい経っているかを示します。
* スケーラビリティと適応性。この要素には、需要の増加に応じてストレージ リソースを段階的に拡張する機能が含まれます。


利用可能なソリューションに関する詳細な技術情報については、以下を参照してください。

* link:vmw-hybrid-dr-nfs.html["NFS データストア向けBlueXP DRaaS を使用した DR"]
* link:vmw-hybrid-dr-vmfs.html["VMFS データストア向けBlueXP DRaaS を使用した DR"]

