---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-use-cases.html 
keywords: NetApp Solutions, ehc, enterprise hybrid cloud, use case, hyperscalers, vmware 
summary:  
---
= VMware を使用したNetAppハイブリッド マルチクラウドのユースケース
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ハイブリッド クラウドまたはクラウド ファーストの展開を計画する際に IT 組織にとって重要なユース ケースの概要。



== 人気のユースケース

使用例は次のとおりです:

* 災害復旧、
* データセンターのメンテナンス中にワークロードをホスティングする、* ローカルデータセンターでプロビジョニングされているリソースを超えて追加のリソースが必要となる急激なバースト、
* VMwareサイトの拡張、
* クラウドへの迅速な移行、
* 開発/テスト、そして
* クラウド補足テクノロジーを活用したアプリの最新化。


このドキュメント全体を通じて、VMware のユースケースを使用してクラウド ワークロードの参照について詳しく説明します。これらのユースケースは次のとおりです。

* 保護（災害復旧とバックアップ/復元の両方を含む）
* 移行
* 拡張




=== ITの旅の内側

ほとんどの組織は変革と近代化への道を歩んでいます。このプロセスの一環として、企業は既存の VMware 投資を活用しながらクラウドのメリットを活用し、移行プロセスを可能な限りシームレスにする方法を模索しています。このアプローチでは、データがすでにクラウド内にあるため、近代化の取り組みが非常に簡単になります。

このシナリオに対する最も簡単な答えは、各ハイパースケーラーで VMware 製品を提供することです。 NetApp Cloud Volumes と同様に、VMware はオンプレミスの VMware 環境を任意のクラウドに移行または拡張する方法を提供しており、既存のオンプレミスの資産、スキル、ツールを保持しながら、クラウドでネイティブにワークロードを実行できます。これにより、サービスの中断や IP 変更の必要がなくなり、IT チームが既存のスキルとツールを使用してオンプレミスと同じように運用できるようになるため、リスクが軽減されます。これにより、クラウド移行が加速され、ハイブリッド マルチクラウド アーキテクチャへの移行がよりスムーズになります。



=== 補足的なNFSストレージオプションの重要性を理解する

どのクラウドでも VMware はすべての顧客に独自のハイブリッド機能を提供しますが、補足的な NFS ストレージ オプションが限られているため、ストレージ負荷の高いワークロードを持つ組織にとってその有用性が制限されています。ストレージはホストに直接結び付けられているため、ストレージを拡張する唯一の方法はホストを追加することであり、これによりストレージを集中的に使用するワークロードのコストが 35 ～ 40% 以上増加する可能性があります。これらのワークロードに必要なのは追加のストレージのみであり、追加の処理能力は必要ありません。しかし、それは追加のホストに料金を支払うことを意味します。

次のシナリオを考えてみましょう。

顧客は CPU とメモリ用に 5 台のホストしか必要としませんが、ストレージのニーズが多く、ストレージ要件を満たすには 12 台のホストが必要です。この要件により、ストレージを増やすだけで済むのに、追加の処理能力を購入しなければならなくなり、財務上の問題が大きくなってしまいます。

クラウドの導入と移行を計画するときは、常に最善のアプローチを評価し、総投資額を削減する最も簡単なパスを採用することが重要です。アプリケーション移行の最も一般的かつ最も簡単なアプローチは、仮想マシン (VM) やデータ変換を行わない再ホスティング (リフト アンド シフトとも呼ばれます) です。  NetApp Cloud Volumes を VMware ソフトウェア定義データセンター (SDDC) と併用することで、vSAN を補完し、簡単なリフトアンドシフト オプションが提供されます。
