---
sidebar: sidebar 
permalink: google/gcp-gcnv-security-considerations.html 
keywords: secure logins, cluster administration, upgrades, data at-rest, mitigation 
summary: データを保護する方法を理解するための最初のステップは、リスクと潜在的な攻撃対象領域を特定することです。 
---
= セキュリティ上の考慮事項と攻撃対象領域
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
データを保護する方法を理解するための最初のステップは、リスクと潜在的な攻撃対象領域を特定することです。

これらには、次のものが含まれます (ただし、これらに限定されません)。

* 管理とログイン
* 保存データ
* 飛行中のデータ
* ネットワークとファイアウォール
* ランサムウェア、マルウェア、ウイルス


攻撃対象領域を理解することで、環境をより安全に保護することができます。  Google Cloud のGoogle Cloud NetApp Volumes はすでにこれらのトピックの多くを考慮しており、管理者の介入なしにデフォルトでセキュリティ機能を実装しています。



== 安全なログインの確保

重要なインフラストラクチャ コンポーネントを保護するときは、承認されたユーザーだけがログインして環境を管理できるようにすることが不可欠です。悪意のある人物が管理者の資格情報を侵害した場合、彼らは城の鍵を入手し、構成の変更、ボリュームとバックアップの削除、バックドアの作成、スナップショット スケジュールの無効化など、何でも実行できるようになります。

Google Cloud NetApp Volumes for Google Cloud は、ストレージ サービス (StaaS) を難読化することで、不正な管理者ログインから保護します。 Google Cloud NetApp Volumes はクラウド プロバイダーによって完全に管理されており、外部からログインすることはできません。すべてのセットアップおよび構成操作は完全に自動化されているため、非常にまれな状況を除いて、人間の管理者がシステムと対話する必要はありません。

ログインが必要な場合、Google Cloud のGoogle Cloud NetApp Volumes は、システムにログインするアクセス権を持つ信頼できる管理者の非常に短いリストを維持することで、ログインを保護します。このゲートキーピングは、アクセス権を持つ潜在的な悪意のある行為者の数を減らすのに役立ちます。さらに、Google Cloud ネットワークはシステムをネットワーク セキュリティの層の背後に隠し、外部には必要なものだけを公開します。  Google Cloud、 Google Cloud NetApp Volumesアーキテクチャの詳細については、次のセクションをご覧ください。link:gcp-gcnv-arch-detail.html["Google Cloud NetApp Volumes のアーキテクチャ。"]



== クラスタ管理とアップグレード

潜在的なセキュリティ リスクがある 2 つの領域には、クラスター管理 (悪意のあるユーザーが管理者アクセス権を取得した場合に何が起こるか) とアップグレード (ソフトウェア イメージが侵害された場合に何が起こるか) が含まれます。



=== ストレージ管理保護

サービスとして提供されるストレージは、クラウド データ センター外部のエンド ユーザーへのアクセスを排除することで、管理者に対する追加の露出リスクを排除します。代わりに、顧客が行う構成は、データ アクセス プレーンに対してのみです。各テナントは独自のボリュームを管理し、どのテナントも他のGoogle Cloud NetApp Volumesインスタンスにアクセスすることはできません。このサービスは自動化によって管理されており、セクションで説明されているプロセスを通じてシステムへのアクセス権が付与される信頼できる管理者のごく少数のリストが存在します。link:gcp-gcnv-service-operation.html["サービス運営。"]

NetApp Volumes-Performance サービス タイプは、リージョン障害が発生した場合に別のリージョンにデータ保護を提供するオプションとして、リージョン間レプリケーションを提供します。このような場合、 Google Cloud NetApp Volumes を影響を受けていないリージョンにフェイルオーバーして、データ アクセスを維持できます。



=== サービスのアップグレード

更新は脆弱なシステムを保護するのに役立ちます。各アップデートでは、攻撃対象領域を最小限に抑えるセキュリティ強化とバグ修正が提供されます。ソフトウェア更新は集中リポジトリからダウンロードされ、更新が許可される前に検証され、公式イメージが使用されていること、およびアップグレードが悪意のある人物によって侵害されていないことが確認されます。

Google Cloud NetApp Volumesでは、更新はクラウド プロバイダ チームによって処理されます。これにより、構成とアップグレードに精通した専門家がプロセスを自動化し、完全にテストすることで、管理者チームのリスク露出が排除されます。アップグレードは中断なく行われ、 Google Cloud NetApp Volumes は最新のアップデートを維持し、全体的に最良の結果を実現します。

これらのサービスアップグレードを実行する管理チームの詳細については、セクションを参照してください。link:gcp-gcnv-service-operation.html["サービス運営。"]



== 保存データの保護

ディスクの盗難、返却、転用に際して保存されている機密データを保護するには、保存データ暗号化が重要です。Google Cloud NetApp Volumes内のデータは、ソフトウェアベースの暗号化を使用して保存時に保護されます。

* Google が生成したキーはNetApp Volumes-SW に使用されます。
* NetApp Volumes-Performance の場合、ボリュームごとのキーはGoogle Cloud NetApp Volumesに組み込まれたキー マネージャーに保存され、 NetApp ONTAP CryptoMod を使用して AES-256 暗号化キーが生成されます。CryptoModはCMVP FIPS 140-2の認定モジュール リストに掲載されています。見る https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4144["FIPS 140-2 証明書 #4144"^]。


2021 年 11 月から、プレビュー版のカスタマー管理暗号化 (CMEK) 機能がNetApp Volumes-Performance で利用できるようになりました。この機能を使用すると、Google Key Management Service（KMS）でホストされているプロジェクトごと、リージョンごとのマスターキーを使用して、ボリュームごとのキーを暗号化できます。  KMS を使用すると、外部キー マネージャーを接続できます。

NetApp Volumes-PerformanceのKMSの設定方法の詳細については、 https://cloud.google.com/architecture/partners/netapp-cloud-volumes/customer-managed-keys?hl=en_US["Google Cloud NetApp Volumesのドキュメントをご覧ください"^] 。

アーキテクチャの詳細については、セクションを参照してください。link:gcp-gcnv-arch-detail.html["Google Cloud NetApp Volumes のアーキテクチャ。"]



=== 転送中のデータの保護

保存中のデータを保護するだけでなく、 Google Cloud NetApp Volumesインスタンスとクライアントまたはレプリケーション ターゲットの間で転送中のデータも保護する必要があります。  Google Cloud NetApp Volumes は、 Kerberos を使用した SMB 暗号化、パケットの署名/シール、NFS Kerberos 5p によるエンドツーエンドのデータ転送暗号化などの暗号化方式を使用して、NAS プロトコル経由で転送中のデータを暗号化します。

Google Cloud NetApp Volumesボリュームのレプリケーションでは、AES-GCM 暗号化方式を利用する TLS 1.2 が使用されます。

Telnet、NDMP などの安全でないインフライト プロトコルのほとんどは、デフォルトで無効になっています。ただし、DNS はGoogle Cloud NetApp Volumesによって暗号化されないため（DNS Sec はサポートされていません）、可能な場合は外部ネットワーク暗号化を使用して暗号化する必要があります。セクションを参照link:gcp-gcnv-data-encrypt-in-transit.html["転送中のデータ暗号化"]転送中のデータのセキュリティ保護の詳細については、こちらをご覧ください。

NASプロトコル暗号化の詳細については、セクションを参照してください。link:gcp-gcnv-data-encrypt-in-transit.html#nas-protocols["NAS プロトコル。"]



== NAS権限のユーザーとグループ

クラウド内のデータのセキュリティ保護には、適切なユーザーおよびグループの認証が含まれます。これにより、データにアクセスするユーザーは環境内の実際のユーザーとして検証され、グループには有効なユーザーが含まれます。これらのユーザーとグループは、初期の共有およびエクスポート アクセス、およびストレージ システム内のファイルとフォルダーに対する権限の検証を提供します。

Google Cloud NetApp Volumes は、 SMB 共有と Windows スタイルの権限に標準の Active Directory ベースの Windows ユーザーおよびグループ認証を使用します。このサービスでは、NFS エクスポート、NFSv4 ID 検証、Kerberos 認証、NFSv4 ACL 用の UNIX ユーザーおよびグループ用の LDAP などの UNIX ID プロバイダーも活用できます。


NOTE: 現在、Google Cloud NetApp Volumes のLDAP 機能では、Active Directory LDAP のみがサポートされています。



== ランサムウェア、マルウェア、ウイルスの検出、防止、軽減

ランサムウェア、マルウェア、ウイルスは管理者にとって継続的な脅威であり、企業組織ではこれらの脅威の検出、防止、軽減が常に最優先事項となっています。重要なデータセットに対する 1 回のランサムウェア攻撃で、数百万ドルの損害が発生する可能性があるため、リスクを最小限に抑えるためにできることを行うことが有益です。

Google Cloud NetApp Volumesには現在、ウイルス対策や https://www.netapp.com/blog/prevent-ransomware-spread-ONTAP/["自動ランサムウェア検出"^]定期的なスナップショット スケジュールを有効にすることで、ランサムウェア イベントから迅速に回復する方法があります。スナップショット コピーは不変であり、ファイル システム内の変更されたブロックへの読み取り専用ポインターです。ほぼ瞬時に実行され、パフォーマンスへの影響は最小限で、データが変更または削除された場合にのみスペースを使用します。希望する許容可能なリカバリポイント目標 (RPO)/リカバリ時間目標 (RTO) に合わせて Snapshot コピーのスケジュールを設定し、ボリュームごとに最大 1,024 個の Snapshot コピーを保持できます。

Google Cloud NetApp Volumesには、スナップショット サポートが追加料金なしで（スナップショット コピーによって保持される変更されたブロック/データに対するデータ ストレージ料金以外）含まれており、ランサムウェア攻撃が発生した場合は、攻撃が発生する前のスナップショット コピーにロールバックするために使用できます。スナップショットの復元はわずか数秒で完了し、その後は通常どおりデータの提供を再開できます。詳細については、以下を参照してください。  https://www.netapp.com/pdf.html?item=/media/16716-sb-3938pdf.pdf&v=202093745["ランサムウェアに対するNetAppソリューション"^] 。

ランサムウェアがビジネスに影響を及ぼすのを防ぐには、次の 1 つ以上の要素を含む多層的なアプローチが必要です。

* エンドポイント保護
* ネットワークファイアウォールによる外部脅威からの保護
* データ異常の検出
* 重要なデータセットの複数のバックアップ（オンサイトおよびオフサイト）
* バックアップの定期的な復元テスト
* 変更不可能な読み取り専用のNetAppスナップショットコピー
* 重要インフラ向け多要素認証
* システムログインのセキュリティ監査


このリストは網羅的なものではありませんが、ランサムウェア攻撃の可能性に対処する際に従うべき良い青写真となります。  Google Cloud のGoogle Cloud NetApp Volumes は、ランサムウェア イベントから保護し、その影響を軽減するためのさまざまな方法を提供します。



=== 不変のスナップショットコピー

Google Cloud NetApp Volumes は、カスタマイズ可能なスケジュールに基づいて作成される不変の読み取り専用スナップショット コピーをネイティブに提供し、データが削除された場合やボリューム全体がランサムウェア攻撃の被害に遭った場合に、迅速なポイントインタイム リカバリを実現します。以前の正常なスナップショット コピーへのスナップショットの復元は高速で、スナップショット スケジュールと RTO/RPO の保持期間に基づいてデータ損失を最小限に抑えます。スナップショット テクノロジによるパフォーマンスへの影響はごくわずかです。

Google Cloud NetApp Volumesのスナップショット コピーは読み取り専用であるため、ランサムウェアが気付かれずにデータセットに侵入し、ランサムウェアに感染したデータのスナップショット コピーが取得されない限り、ランサムウェアに感染することはありません。このため、データの異常に基づくランサムウェア検出も検討する必要があります。  Google Cloud NetApp Volumes は現在ネイティブ検出機能を提供していませんが、外部監視ソフトウェアを使用できます。



=== バックアップおよびリストア

Google Cloud NetApp Volumes は、標準の NAS クライアント バックアップ機能（NFS または SMB 経由のバックアップなど）を提供します。

* NetApp Volumes-Performance は、他のNetApp Volumes-Performance ボリュームへのリージョン間ボリュームレプリケーションを提供します。詳細については、 https://cloud.google.com/architecture/partners/netapp-cloud-volumes/volume-replication?hl=en_US["ボリュームレプリケーション"^] Google Cloud NetApp Volumes のドキュメントをご覧ください。
* NetApp Volumes-SW は、サービスネイティブのボリューム バックアップ/リストア機能を提供します。詳細については、 https://cloud.google.com/architecture/partners/netapp-cloud-volumes/back-up?hl=en_US["クラウドバックアップ"^] Google Cloud NetApp Volumes のドキュメントをご覧ください。


ボリューム レプリケーションは、ランサムウェア イベントなどの災害発生時に高速フェイルオーバーを実現するために、ソース ボリュームの正確なコピーを提供します。



=== クロスリージョンレプリケーション

NetApp Volumes-Performance を使用すると、Google のネットワークで実行されるレプリケーションに使用される特定のインターフェースを使用して、 NetAppが管理するバックエンド サービス ネットワーク上で TLS1.2 AES 256 GCM 暗号化を使用することで、データ保護とアーカイブのユースケースのために Google Cloud リージョン間でボリュームを安全に複製できます。プライマリ (ソース) ボリュームにはアクティブな本番データが含まれており、セカンダリ (宛先) ボリュームに複製されてプライマリ データセットの正確なレプリカが提供されます。

初期レプリケーションではすべてのブロックが転送されますが、更新ではプライマリ ボリューム内の変更されたブロックのみが送信されます。たとえば、プライマリ ボリュームにある 1 TB のデータベースがセカンダリ ボリュームに複製される場合、最初のレプリケーションで 1 TB の領域が転送されます。そのデータベースに、初期化と次回の更新の間に変更される数百行 (仮に数 MB) がある場合、変更された行を含むブロックのみがセカンダリ (数 MB) に複製されます。これにより、転送時間が短くなり、レプリケーション料金が抑えられます。

ファイルとフォルダーに対するすべてのアクセス許可はセカンダリ ボリュームに複製されますが、共有アクセス アクセス許可 (エクスポート ポリシーとルール、SMB 共有と共有 ACL など) は個別に処理する必要があります。サイトのフェールオーバーの場合、宛先サイトでは同じ名前サービスと Active Directory ドメイン接続を活用して、ユーザーとグループの ID およびアクセス許可を一貫して処理する必要があります。レプリケーション関係を解除してセカンダリ ボリュームを読み取り/書き込み可能に変換することで、災害発生時にセカンダリ ボリュームをフェイルオーバー ターゲットとして使用できます。

ボリューム レプリカは読み取り専用であり、ウイルスがデータに感染した場合やランサムウェアがプライマリ データセットを暗号化した場合に、データを迅速に回復できるように、オフサイトでデータの不変のコピーを提供します。読み取り専用データは暗号化されませんが、プライマリ ボリュームが影響を受けてレプリケーションが発生すると、感染したブロックも複製されます。影響を受けていない古いスナップショット コピーを使用して回復することもできますが、攻撃の検出速度によっては、SLA が約束された RTO/RPO の範囲外になる可能性があります。

さらに、Google Cloud のクロスリージョン レプリケーション（CRR）管理により、ボリュームの削除、スナップショットの削除、スナップショットのスケジュール変更などの悪意のある管理アクションを防ぐことができます。これは、ソース ボリュームを削除できるがミラーを解除できないため宛先ボリュームを削除できないボリューム管理者と、ボリューム操作を一切実行できない CRR 管理者を分離するカスタム ロールを作成することによって行われます。見る https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["セキュリティに関する考慮事項"^]各管理者グループで許可される権限については、 Google Cloud NetApp Volumes のドキュメントをご覧ください。



=== Google Cloud NetApp Volumesバックアップ

Google Cloud NetApp Volumes は高いデータ耐久性を提供しますが、外部イベントによってデータが失われる可能性があります。ウイルスやランサムウェアなどのセキュリティ イベントが発生した場合、データ アクセスをタイムリーに再開するには、バックアップと復元が重要になります。管理者がGoogle Cloud NetApp Volumesボリュームを誤って削除してしまう可能性があります。あるいは、ユーザーはデータのバックアップ バージョンを数か月間保持したいだけなので、ボリューム内に追加のスナップショット コピー スペースを保持するとコスト上の課題が発生します。スナップショット コピーは、失われたデータを復元するために過去数週間のバックアップ バージョンを保持するのに適した方法ですが、スナップショット コピーはボリューム内に保存されるため、ボリュームが消失すると失われます。

これらの理由から、 Google Cloud NetApp Volumesは、 https://cloud.google.com/architecture/partners/netapp-cloud-volumes/back-up?hl=en_US["Google Cloud NetApp Volumesバックアップ"^] 。

Google Cloud NetApp Volumesバックアップでは、Google Cloud Storage (GCS) 上にボリュームのコピーが生成されます。ボリューム内に保存されている実際のデータのみがバックアップされ、空き領域はバックアップされません。これは永久増分として機能します。つまり、ボリュームの内容を一度転送し、それ以降は変更されたデータのみをバックアップし続けます。複数の完全バックアップを伴う従来のバックアップ概念と比較すると、大量のバックアップストレージを節約し、コストを削減します。バックアップ スペースの月額料金はボリュームに比べて低いため、バックアップ バージョンを長期間保存するのに最適な場所です。

ユーザーは、 Google Cloud NetApp Volumesバックアップを使用して、同じリージョン内の同じボリュームまたは別のボリュームに任意のバックアップ バージョンを復元できます。ソースボリュームが削除された場合でも、バックアップデータは保持されるため、個別に管理（削除など）する必要があります。

Google Cloud NetApp Volumesバックアップは、オプションとしてGoogle Cloud NetApp Volumesに組み込まれています。ユーザーは、ボリュームごとにGoogle Cloud NetApp Volumesバックアップを有効にすることで、保護するボリュームを決定できます。参照 https://cloud.google.com/architecture/partners/netapp-cloud-volumes/back-up?hl=en_US["Google Cloud NetApp Volumesバックアップのドキュメント"^]バックアップの詳細については、 https://cloud.google.com/architecture/partners/netapp-cloud-volumes/resource-limits-quotas?hl=en_US["サポートされる最大バックアップバージョンの数"^] 、スケジュール、そして https://cloud.google.com/architecture/partners/netapp-cloud-volumes/costs?hl=en_US["価格設定"^]。

プロジェクトのすべてのバックアップ データは GCS バケット内に保存されます。このバケットはサービスによって管理され、ユーザーには表示されません。各プロジェクトは異なるバケットを使用します。現在、バケットはGoogle Cloud NetApp Volumesボリュームと同じリージョンにありますが、さらに多くのオプションが検討されています。最新のステータスについてはドキュメントを参照してください。

Google Cloud NetApp Volumesバケットから GCS へのデータ転送には、HTTPS と TLS1.2 を使用したサービス内部の Google ネットワークが使用されます。データは Google が管理するキーを使用して保存時に暗号化されます。

Google Cloud NetApp Volumesのバックアップ（バックアップの作成、削除、復元）を管理するには、ユーザーは https://cloud.google.com/architecture/partners/netapp-cloud-volumes/security-considerations?hl=en_US["ロール/netappcloudvolumes.admin"^]役割。
