---
sidebar: sidebar 
permalink: google/gcp-gcnv-nas-basics.html 
keywords: nas, basics, gcp, nfs, smb 
summary: NAS プロトコルは、ネットワーク上の複数のクライアントが、GCP 上のGoogle Cloud NetApp Volumesなどのストレージ システム上の同じデータにアクセスするための方法です。  NFS と SMB は定義された NAS プロトコルであり、 Google Cloud NetApp Volumes がサーバーとして機能するクライアント/サーバー ベースで動作します。 
---
= NASプロトコルの基礎
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NAS プロトコルは、ネットワーク上の複数のクライアントが、GCP 上のGoogle Cloud NetApp Volumesなどのストレージ システム上の同じデータにアクセスするための方法です。 NFS と SMB は定義された NAS プロトコルであり、 Google Cloud NetApp Volumes がサーバーとして機能するクライアント/サーバー ベースで動作します。クライアントはアクセス、読み取り、書き込みの要求をサーバーに送信し、サーバーはファイルのロック メカニズムの調整、アクセス許可の保存、ID および認証要求の処理を担当します。

たとえば、NAS クライアントがフォルダー内に新しいファイルを作成する場合は、次の一般的なプロセスが実行されます。

. クライアントはサーバーにディレクトリに関する情報 (権限、所有者、グループ、ファイル ID、使用可能なスペースなど) を要求します。サーバーは、要求元のクライアントとユーザーが親フォルダーに対する必要な権限を持っている場合に、その情報で応答します。
. ディレクトリの権限でアクセスが許可されている場合、クライアントは、作成するファイル名がファイル システムにすでに存在するかどうかをサーバーに問い合わせます。ファイル名がすでに使用されている場合、作成は失敗します。ファイル名が存在しない場合は、サーバーはクライアントに処理を続行できることを通知します。
. クライアントは、ディレクトリ ハンドルとファイル名を使用してファイルを作成するためにサーバーに呼び出しを発行し、アクセス時刻と変更時刻を設定します。サーバーはファイルに一意のファイル ID を発行し、同じファイル ID を持つ他のファイルが作成されないようにします。
. クライアントは、WRITE 操作の前にファイル属性を確認するための呼び出しを送信します。権限が許可されている場合、クライアントは新しいファイルを書き込みます。プロトコル/アプリケーションによってロックが使用される場合、クライアントは、データの破損を防ぐためにロックされている間に他のクライアントがファイルにアクセスできないようにするために、サーバーにロックを要求します。

