---
sidebar: sidebar 
permalink: videos/hmc-aws-videos.html 
summary: NetAppを使用した AWS ハイブリッド マルチクラウド ソリューションを紹介するビデオとデモ 
keywords: hybrid cloud, rosa, fsx ontap, azure vmware, netapp hci, videos, demos 
---
= NetAppを使用した Amazon Web Services 向けハイブリッド マルチクラウド ソリューションに関するビデオを見る
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetAppによる AWS 向けハイブリッド マルチクラウド ソリューションを紹介する NetApp の包括的なビデオ ライブラリをご覧ください。ゲスト接続ストレージ、TCO 削減、補足データストア、VMware Cloud on AWS およびAmazon FSx for ONTAPの移行ワークフロー（Windows および Linux のシナリオを含む）に関するビデオをご覧ください。



== ゲスト接続ストレージ

.iSCSI を使用した FSx ONTAPによる Windows ゲスト接続ストレージ
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.NFS を使用した FSx ONTAPによる Linux ゲスト接続ストレージ
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]


== TCOと補足データストア

.Amazon FSx ONTAPによる VMware Cloud on AWS の TCO 削減
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.VMware Cloud on AWS 補足データストア ( Amazon FSx ONTAP搭載)
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]


== 移行ワークフロー (HCX)

.VMC 向けの VMware HCX の展開と構成のセットアップ
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.VMC および FSx ONTAP向け VMware HCX を使用した vMotion 移行のデモンストレーション
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.VMC および FSx ONTAP向け VMware HCX を使用したコールド マイグレーションのデモンストレーション
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]